services:
  - type: web
    name: nextcar-dashboard-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nextcar-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: nextcar-db
    databaseName: nextcar
    user: nextcar
    plan: free
